.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH MXIOSTAT 1 "July 13, 2011"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
mxiostat \- Report reliable kernel disk IO statistics
.SH SYNOPSIS
.SY mxiostat
.OP \-qvaH
.OP \-D DEV,...
.OP \-c COUNT
.RI [[DEV|FIELD,...]
.RI [DELAY]]
.SH DESCRIPTION
.B mxiostat
is a version of iostat's disk IO statistics that actually reports real
numbers for disk IO that are taken straight from the kernel. It requires
a Linux 2.6 kernel. On relatively recent 2.6 kernels, it can also report
full per-partition IO statistics; on older kernels, per-partition stats
are incomplete.
.\" TODO: determine which kernel version is required
.SH ARGUMENTS
Which form of arguments is used depends on the command line options.
Without options
.B mxiostat
reports on a single device and you can supply
.IR DEV .
With
.BR \-a ,
mxiostat reports on all disks (unless you specify a subset) and you
can supply
.IR FIELD
(or multiple fields, comma separated).
.TP
.I DELAY
The delay between reports, in seconds. Defaults to 1 second.
.TP
.I DEV
Device names are given without the leading /dev, ie simply 'sda'. The
default device is sda.
.TP
.I FIELD
The field (or fields, with comma separation). See below for what fields
are available. The special field name
.B all
means 'all available normal fields'. The default field depends on the
specific command line ptions; see below.
.SH OPTIONS
A summary of options is included below.
.TP
.B -q
Don't print the periodic header.
.TP
.B -v
Be more verbose in some situations.
.TP
.BI -c COUNT
Exit after printing COUNT reports.
.TP
.B \-a
Report on particular stat(s) for all disks, instead of all stats for
one disk. In this mode the default field to report on is
.BR util .
.TP
.B \-C
Compact reporting for multiple fields in
.B \-a
mode; all fields for all disks are printed on one line.
.TP
.B \-V
Produce a 'vertical' report for multiple disks in -a mode, where each
disk is printed on a separate line. In this mode the default field to
report on is
.BR all ,
ie all fields.
.TP
.BI \-D DEV,...
In
.BR \-a ,
report on only these device(s) instead of all devices
.TP
.BI \-X DEV,...
In
.BR \-a ,
exclude these devices from the report
.TP
.I DELAY
The number of seconds between report lines
.PP
.SH FIELD VALUES AND WHAT THEY MEAN
.SS
.B rio
.nf
number of read IO requests completed
.fi
.PP
.SS
.B rmerge
.nf
Number of submitted read requests that were merged into
existing requests.
.fi
.PP
.SS
.B rsect
.nf
Number of read IO sectors submitted (always 512-byte sectors)
.fi
.PP
.SS
.B rgrp
.nf
rsect / rio, average number of sectors per request (more or less)
.fi
.PP
.SS
.B rwait
.nf
average wait time for read requests in milliseconds
.fi
.PP
.SS
.B  w*
.nf
as with the r* versions, but for writes
.fi
.PP
.SS
.B agrp
.nf
Overall average number of sectors per request
.fi
.PP
.SS
.B await
.nf
overall average wait time for requests in milliseconds
.fi
.PP
.SS
.B aio
.nf
overall requests submitted (rio + wio)
.fi
.PP
.SS
.B asect
.nf
overall sector count (rsect + wsect)
.fi
.PP
.SS
.B act
.nf
number of IO requests in the queue at this instant
.fi
.PP
.SS
.B aveq
.nf
average number of requests in the queue
.fi
.PP
.SS
.B util
.nf
percent utilization of the drive (ie, % busy)
.fi
.BR
.SH NOTES
Most of these fields are whatever-per-second; act is an instantaneous
number. See also http://utcc.utoronto.ca/~cks/space/blog/linux/DiskIOStats
for some additional notes and exact details.
.SH FILES
.ta
.nf
/proc/diskstats
.fi

.SH SEE ALSO
.BR iostat (1),
.SH AUTHOR
mxiostat was written by Chris Siebenmann <cks.git01@cs.toronto.edu>
.PP
This manual page was written by John Cooper <john@choffee.co.uk>
(with subsequent mangling by Chris Siebenmann)
